### ISSUE TITLE
Add CI tests to check if links exist

### ISSUE THREAD

**Issue by paramt** [paramt/projects#7]
Loop through each URL in the CSV file and check if exists using this code:

```shell
if curl --output /dev/null --silent --head --fail "$url"; then
  echo "URL exists: $url"
else
  echo "URL does not exist: $url"
fi
```

[Cirrus CI](https://cirrus-ci.com/) looks like a good option for this

**Comment by RDIL** [comment]
Cirrus*

**Comment by paramt** [comment]
Closed by https://github.com/paramt/projects/commit/e105aa20519c02032a3afda3a9f8abc1a5c3068a
